//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICBackend.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ContosoUniversityDataEntities1 : DbContext
    {
        public ContosoUniversityDataEntities1()
            : base("name=ContosoUniversityDataEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<Enrollment> Enrollments { get; set; }
        public virtual DbSet<Student> Students { get; set; }
    
        public virtual int Sp_Course_Delete(Nullable<int> pId)
        {
            var pIdParameter = pId.HasValue ?
                new ObjectParameter("pId", pId) :
                new ObjectParameter("pId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Course_Delete", pIdParameter);
        }
    
        public virtual ObjectResult<Sp_Course_Retrieve_Result> Sp_Course_Retrieve(Nullable<int> pId, string pKey)
        {
            var pIdParameter = pId.HasValue ?
                new ObjectParameter("pId", pId) :
                new ObjectParameter("pId", typeof(int));
    
            var pKeyParameter = pKey != null ?
                new ObjectParameter("pKey", pKey) :
                new ObjectParameter("pKey", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Course_Retrieve_Result>("Sp_Course_Retrieve", pIdParameter, pKeyParameter);
        }
    
        public virtual int Sp_Courses_AddOrEdit(Nullable<int> pId, string pTitle, Nullable<int> pCredits, byte[] pRowVersion)
        {
            var pIdParameter = pId.HasValue ?
                new ObjectParameter("pId", pId) :
                new ObjectParameter("pId", typeof(int));
    
            var pTitleParameter = pTitle != null ?
                new ObjectParameter("pTitle", pTitle) :
                new ObjectParameter("pTitle", typeof(string));
    
            var pCreditsParameter = pCredits.HasValue ?
                new ObjectParameter("pCredits", pCredits) :
                new ObjectParameter("pCredits", typeof(int));
    
            var pRowVersionParameter = pRowVersion != null ?
                new ObjectParameter("pRowVersion", pRowVersion) :
                new ObjectParameter("pRowVersion", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Courses_AddOrEdit", pIdParameter, pTitleParameter, pCreditsParameter, pRowVersionParameter);
        }
    
        public virtual int Sp_Enrollment_AddOrEdit(Nullable<int> pId, Nullable<decimal> pGrade, Nullable<int> pCourseID, Nullable<int> pStudentID, byte[] pRowVersion)
        {
            var pIdParameter = pId.HasValue ?
                new ObjectParameter("pId", pId) :
                new ObjectParameter("pId", typeof(int));
    
            var pGradeParameter = pGrade.HasValue ?
                new ObjectParameter("pGrade", pGrade) :
                new ObjectParameter("pGrade", typeof(decimal));
    
            var pCourseIDParameter = pCourseID.HasValue ?
                new ObjectParameter("pCourseID", pCourseID) :
                new ObjectParameter("pCourseID", typeof(int));
    
            var pStudentIDParameter = pStudentID.HasValue ?
                new ObjectParameter("pStudentID", pStudentID) :
                new ObjectParameter("pStudentID", typeof(int));
    
            var pRowVersionParameter = pRowVersion != null ?
                new ObjectParameter("pRowVersion", pRowVersion) :
                new ObjectParameter("pRowVersion", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Enrollment_AddOrEdit", pIdParameter, pGradeParameter, pCourseIDParameter, pStudentIDParameter, pRowVersionParameter);
        }
    
        public virtual int Sp_Enrollment_Delete(Nullable<int> pId)
        {
            var pIdParameter = pId.HasValue ?
                new ObjectParameter("pId", pId) :
                new ObjectParameter("pId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Enrollment_Delete", pIdParameter);
        }
    
        public virtual ObjectResult<Sp_Enrollment_Retrieve_Result> Sp_Enrollment_Retrieve(Nullable<int> pId, string pKey)
        {
            var pIdParameter = pId.HasValue ?
                new ObjectParameter("pId", pId) :
                new ObjectParameter("pId", typeof(int));
    
            var pKeyParameter = pKey != null ?
                new ObjectParameter("pKey", pKey) :
                new ObjectParameter("pKey", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Enrollment_Retrieve_Result>("Sp_Enrollment_Retrieve", pIdParameter, pKeyParameter);
        }
    
        public virtual int Sp_Student_Delete(Nullable<int> pId)
        {
            var pIdParameter = pId.HasValue ?
                new ObjectParameter("pId", pId) :
                new ObjectParameter("pId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Student_Delete", pIdParameter);
        }
    
        public virtual ObjectResult<Sp_Student_Retrieve_Result> Sp_Student_Retrieve(Nullable<int> pId, string pKey)
        {
            var pIdParameter = pId.HasValue ?
                new ObjectParameter("pId", pId) :
                new ObjectParameter("pId", typeof(int));
    
            var pKeyParameter = pKey != null ?
                new ObjectParameter("pKey", pKey) :
                new ObjectParameter("pKey", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Student_Retrieve_Result>("Sp_Student_Retrieve", pIdParameter, pKeyParameter);
        }
    
        public virtual int Sp_Student_AddOrEdit(Nullable<int> pId, string pFirstName, string pLastName, string pMiddleName, Nullable<System.DateTime> pEnrollmentDate)
        {
            var pIdParameter = pId.HasValue ?
                new ObjectParameter("pId", pId) :
                new ObjectParameter("pId", typeof(int));
    
            var pFirstNameParameter = pFirstName != null ?
                new ObjectParameter("pFirstName", pFirstName) :
                new ObjectParameter("pFirstName", typeof(string));
    
            var pLastNameParameter = pLastName != null ?
                new ObjectParameter("pLastName", pLastName) :
                new ObjectParameter("pLastName", typeof(string));
    
            var pMiddleNameParameter = pMiddleName != null ?
                new ObjectParameter("pMiddleName", pMiddleName) :
                new ObjectParameter("pMiddleName", typeof(string));
    
            var pEnrollmentDateParameter = pEnrollmentDate.HasValue ?
                new ObjectParameter("pEnrollmentDate", pEnrollmentDate) :
                new ObjectParameter("pEnrollmentDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Student_AddOrEdit", pIdParameter, pFirstNameParameter, pLastNameParameter, pMiddleNameParameter, pEnrollmentDateParameter);
        }
    }
}
